server:
  port: 8888

spring:
  application:
    name: config-service
  # profiles:
  #   active: native  # This line is not needed for Git configuration; it's typically for native file-based config.

  cloud:
    config:
      uri: http://localhost  # Not needed in the GitHub config file. This should be in the client services' bootstrap.yml.
      label: main  # This should be default-label: "main" if you are using the main branch. 

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.20.29}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:epic_ipg}
    username: ${MYSQL_USERNAME:epicpay}
    password: ${MYSQL_PASSWORD:Password@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
