server:
  port: 8081

spring:
  application:
    name: "gateway-service"
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8888/}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: merchant-service
          uri: lb://merchant-service
          predicates:
            - Path=/api/v1/merchant/**
          filters:
            - StripPrefix=3

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=3

        - id: ipg-engine
          uri: lb://ipg-engine
          predicates:
            - Path=/api/v1/ipg/**
          filters:
            - StripPrefix=3

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gateway-service"
    description: "EpicPAY Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      epic:
        gateway: DEBUG