server:
  port: 8082
  path: /api/v1/merchant

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.20.29}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:epic_ipg}
    username: ${MYSQL_USERNAME:epicpay}
    password: ${MYSQL_PASSWORD:Password@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false
app:
  welcomeMsg: Hello from the client configuration application(DEV Environment).
  version: V1.00.00.0

# JWT Configurations
jwt:
  secret:
    key: 4d18dc1f7aeb498671077ac77227a985d38ac11e6c18686c3fa1562990419e5c
  expiration:
    time: 1440

logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN
    com:
      epic:
        merchant: TRACE
    org.springframework.boot.context.properties: DEBUG
  file:
    path: ${file.root.path}/LOGS

file:
  root:
    path: /opt
  max:
    file-size: 1024MB
  upload-dir: ${file.root.path}/FILES/
  temp-dir: ${file.root.path}/TEMP_FILES/
  error-dir: ${file.root.path}/LOGS/ERROR/
  encodekey: h8hGqKO/jMriLddfo7xNIg==

server-url:
  http://192.168.20.29

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

openapi:
  service:
    title: EPIC PAY IPG - MERCHANT SERVICE
    version:  V1.00.00.0
    url: ${GATEWAY_SERVICE_URI:http://localhost:8081}
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
