server:
  port: 8083
  path: /api/v1/notification

app:
  version: V1.00.00.0

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.20.29}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:epic_ipg}
    username: ${MYSQL_USERNAME:epicpay}
    password: ${MYSQL_PASSWORD:Password@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: epicmailsender@gmail.com
    password: zxgxtijlxpbrfdic
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
openapi:
  service:
    title: EPIC PAY IPG - NOTIFICATION SERVICE
    version:  V1.00.00.0
    url: ${GATEWAY_SERVICE_URI:http://localhost:8081}
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    enabled: true
eureka:
  #  instance:
  #    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

# SMS Service Configuration
sms:
  api:
    host: ${SMS_HOST:}
    key: ${SMS_KEY:}
